name: Build and Deploy

on:
  push:
    branches: [ "main" ] # or "master"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies and Build
        run: |
          cd client
          npm install --legacy-peer-deps
          npm run build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: client/dist # Change to client/build if using Create React App
          branch: gh-pages